# Generated by Django 3.1.4 on 2021-02-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, null=True, verbose_name='作業項目')),
            ],
            options={
                'verbose_name': '作業項目',
                'verbose_name_plural': '作業項目',
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=50, null=True, verbose_name='作業方法')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.item')),
            ],
            options={
                'verbose_name': '作業方法',
                'verbose_name_plural': '作業方法',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50, null=True, verbose_name='セクション')),
            ],
            options={
                'verbose_name': 'セクション',
                'verbose_name_plural': 'セクション',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.TextField(max_length=50, null=True, verbose_name='作業手順')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='作業映像')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/', verbose_name='作業動画')),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.method')),
            ],
            options={
                'verbose_name': '作業手順',
                'verbose_name_plural': '作業手順',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50, null=True, verbose_name='作業名')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.section')),
            ],
            options={
                'verbose_name': '作業名',
                'verbose_name_plural': '作業名',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.job'),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField(blank=True, max_length=50, null=True, verbose_name='ポイント')),
                ('caution', models.TextField(blank=True, max_length=50, null=True, verbose_name='注意点')),
                ('tips', models.TextField(blank=True, max_length=50, null=True, verbose_name='コツ')),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.procedure')),
            ],
            options={
                'verbose_name': 'ポイント',
                'verbose_name_plural': 'ポイント',
            },
        ),
    ]
