# Generated by Django 3.1.4 on 2021-02-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, null=True, verbose_name='3.作業項目')),
                ('purpose', models.CharField(blank=True, max_length=100, null=True, verbose_name='目的')),
                ('success', models.CharField(blank=True, max_length=100, null=True, verbose_name='達成基準')),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': '3.作業項目',
                'verbose_name_plural': '3.作業項目',
                'ordering': ['the_order'],
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=50, null=True, verbose_name='4.作業方法')),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.item')),
            ],
            options={
                'verbose_name': '4.作業方法',
                'verbose_name_plural': '4.作業方法',
                'ordering': ['the_order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50, null=True, verbose_name='1.セクション')),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': '1.セクション',
                'verbose_name_plural': '1.セクション',
                'ordering': ['the_order'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.TextField(max_length=200, null=True, verbose_name='5.作業手順')),
                ('point', models.TextField(blank=True, max_length=200, null=True, verbose_name='ポイント')),
                ('caution', models.TextField(blank=True, max_length=200, null=True, verbose_name='注意点')),
                ('tips', models.TextField(blank=True, max_length=200, null=True, verbose_name='コツ')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='画像')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/', verbose_name='動画')),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='manual.method')),
            ],
            options={
                'verbose_name': '5.作業手順',
                'verbose_name_plural': '5.作業手順',
                'ordering': ['the_order'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50, null=True, verbose_name='2.作業名')),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.section')),
            ],
            options={
                'verbose_name': '2.作業名',
                'verbose_name_plural': '2.作業名',
                'ordering': ['the_order'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.job'),
        ),
    ]
