# Generated by Django 3.1.4 on 2021-02-24 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.section', verbose_name='属するセクション'),
        ),
        migrations.AddField(
            model_name='method',
            name='method_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.job', verbose_name='属する作業名'),
        ),
        migrations.AddField(
            model_name='method',
            name='method_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.section', verbose_name='属するセクション'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='procedure_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.item', verbose_name='属する作業項目'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='procedure_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.job', verbose_name='属する作業名'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='procedure_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.section', verbose_name='属するセクション'),
        ),
        migrations.AlterField(
            model_name='item',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.job', verbose_name='属する作業名'),
        ),
        migrations.AlterField(
            model_name='method',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.item', verbose_name='属する作業項目'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='manual.method', verbose_name='属する作業方法'),
        ),
    ]
