# Generated by Django 3.1.4 on 2021-02-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='caution',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='注意点'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='point',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='ポイント'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='tips',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='コツ'),
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
    ]
