# Generated by Django 3.1.4 on 2021-02-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0002_auto_20210215_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['the_order'], 'verbose_name': '作業項目', 'verbose_name_plural': '作業項目'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['the_order'], 'verbose_name': '作業名', 'verbose_name_plural': '作業名'},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['the_order'], 'verbose_name': '作業方法', 'verbose_name_plural': '作業方法'},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['the_order'], 'verbose_name': '作業手順', 'verbose_name_plural': '作業手順'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['the_order'], 'verbose_name': 'セクション', 'verbose_name_plural': 'セクション'},
        ),
        migrations.AddField(
            model_name='item',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='job',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='method',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='procedure',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='section',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
