# Generated by Django 3.1.4 on 2021-03-29 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0003_auto_20210301_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.job', verbose_name='属する項目'),
        ),
        migrations.AlterField(
            model_name='job',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.section', verbose_name='属する項目'),
        ),
        migrations.AlterField(
            model_name='method',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='method', to='manual.item', verbose_name='属する項目'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='manual.method', verbose_name='属する項目'),
        ),
    ]
