# Generated by Django 3.1.4 on 2021-02-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0003_auto_20210215_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['the_order'], 'verbose_name': '3.作業項目', 'verbose_name_plural': '3.作業項目'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['the_order'], 'verbose_name': '2.作業名', 'verbose_name_plural': '2.作業名'},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['the_order'], 'verbose_name': '4.作業方法', 'verbose_name_plural': '4.作業方法'},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['the_order'], 'verbose_name': '5.作業手順', 'verbose_name_plural': '5.作業手順'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['the_order'], 'verbose_name': '1.セクション', 'verbose_name_plural': '1.セクション'},
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=50, null=True, verbose_name='3.作業項目'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(max_length=50, null=True, verbose_name='2.作業名'),
        ),
        migrations.AlterField(
            model_name='method',
            name='method_name',
            field=models.CharField(max_length=50, null=True, verbose_name='4.作業方法'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='procedure_name',
            field=models.TextField(max_length=50, null=True, verbose_name='5.作業手順'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=50, null=True, verbose_name='1.セクション'),
        ),
    ]
