# Generated by Django 3.1.4 on 2021-02-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0004_auto_20210215_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='purpose',
            field=models.CharField(max_length=20, null=True, verbose_name='目的'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='success',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='達成基準'),
        ),
    ]
