# Generated by Django 3.1.4 on 2021-09-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0004_auto_20210329_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purpose',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='目的'),
        ),
        migrations.AlterField(
            model_name='item',
            name='success',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='達成基準'),
        ),
    ]
