# Generated by Django 3.1.4 on 2021-02-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0005_auto_20210217_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='purpose',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='目的'),
        ),
    ]
