# Generated by Django 3.1.4 on 2021-02-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0007_auto_20210218_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='success',
        ),
        migrations.AddField(
            model_name='method',
            name='purpose',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='目的'),
        ),
        migrations.AddField(
            model_name='method',
            name='success',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='達成基準'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='caution',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='注意点'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='point',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='ポイント'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='procedure_name',
            field=models.TextField(max_length=200, null=True, verbose_name='5.作業手順'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='tips',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='コツ'),
        ),
    ]
