# Generated by Django 3.1.4 on 2021-02-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0008_auto_20210218_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='目的'),
        ),
        migrations.AlterField(
            model_name='method',
            name='success',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='達成基準'),
        ),
    ]
