# Generated by Django 3.1.4 on 2021-02-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0009_auto_20210218_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='method',
            name='success',
        ),
        migrations.AddField(
            model_name='item',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='目的'),
        ),
        migrations.AddField(
            model_name='item',
            name='success',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='達成基準'),
        ),
    ]
