# Generated by Django 3.1.4 on 2021-02-21 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0010_auto_20210219_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='manual.section'),
        ),
    ]
