# Generated by Django 3.1.4 on 2021-02-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0012_auto_20210222_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/', verbose_name='動画'),
        ),
    ]
