# Generated by Django 3.1.4 on 2021-02-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0013_auto_20210222_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='job_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.section'),
        ),
    ]
