# Generated by Django 3.1.4 on 2021-03-01 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0015_auto_20210224_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_section',
        ),
        migrations.RemoveField(
            model_name='method',
            name='method_job',
        ),
        migrations.RemoveField(
            model_name='method',
            name='method_section',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='procedure_item',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='procedure_job',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='procedure_section',
        ),
    ]
